exclude-paths:
  cdk:
    pattern: cdk.out
    default: true
  node-modules:
    pattern: node_modules
    default: true
  git:
    pattern: .git
    default: true
  venv:
    pattern: .venv
    default: true
  cover:
    pattern: cover
    default: true
  serverless:
    pattern: .serverless
    default: true

ignore-files:
  autosave:
    pattern: "*~"
    default: true
  temp-sockets:
    pattern: ".#*"
    default: true
  emacs-temp:
    pattern: "#*#"
    default: true
  d-ts:
    pattern: "*.d.ts"
    default: true
  js:
    pattern: "*.js"
    default: true
  locks:
    pattern:
      - package-lock.json
      - yarn.lock
      - Pipfile.lock
    default: true
  tests:
    pattern:
      - "test_*.py"
      - "*_test.go"
    default: true

select-files:
  go:
    pattern: "*.go"
    mutex-group: select
  python:
    pattern: "*.py"
    mutex-group: select
  typescript:
    pattern: "*.ts"
    mutex-group: select
  java:
    pattern: "*.java"
    mutex-group: select
  graphql:
    pattern: "*.graphql"
    mutex-group: select
  elisp:
    pattern: "*.el"
    mutex-group: select

grep:
  ignore-binary:
    target: -I
    default: true
  show-lines:
    target: -n
    default: true
  show-filename:
    target: -H
    default: true
  filenames-only:
    target: -l
  fixed-string:
    target: -F
    mutex-group: pattern
  extended-regexp:
    target: -E
    mutex-group: pattern
  perl-regexp:
    target: -P
    mutex-group: pattern
  whole-word:
    target: -w
  ignore-case:
    target: -i
  before:
    target: -B
    type: int
  after:
    target: -A
    type: int
  color:
    target: --color=
    type: str
    allowed-values:
      - always
      - never
      - auto
    default: always
